// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seppo_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SeppoService {

  /// <summary>Holder for reflection information generated from seppo_service.proto</summary>
  public static partial class SeppoServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for seppo_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SeppoServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNzZXBwb19zZXJ2aWNlLnByb3RvEgxTZXBwb1NlcnZpY2UaEWV3X2RhdGFi",
            "YXNlLnByb3RvGg1ld19zb25nLnByb3RvGg5ld192ZXJzZS5wcm90bzLHAQoF",
            "U2VwcG8SXwoWbGlzdGVuRm9yQ2hhbmdlZEV3U29uZxIrLlNlcHBvU2Vydmlj",
            "ZS5MaXN0ZW5Gb3JDaGFuZ2VkRXdTb25nUmVxdWVzdBoULlNlcHBvU2Vydmlj",
            "ZS5Fd1NvbmciADABEl0KDnN5bmNFd0RhdGFiYXNlEiMuU2VwcG9TZXJ2aWNl",
            "LlN5bmNFd0RhdGFiYXNlUmVxdWVzdBokLlNlcHBvU2VydmljZS5TeW5jRXdE",
            "YXRhYmFzZVJlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SeppoService.EwDatabaseReflection.Descriptor, global::SeppoService.EwSongReflection.Descriptor, global::SeppoService.EwVerseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
