// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ew_verse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SeppoService {

  /// <summary>Holder for reflection information generated from ew_verse.proto</summary>
  public static partial class EwVerseReflection {

    #region Descriptor
    /// <summary>File descriptor for ew_verse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EwVerseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5ld192ZXJzZS5wcm90bxIMU2VwcG9TZXJ2aWNlIhgKB0V3VmVyc2USDQoF",
            "dmVyc2UYASABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SeppoService.EwVerse), global::SeppoService.EwVerse.Parser, new[]{ "Verse" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EwVerse : pb::IMessage<EwVerse> {
    private static readonly pb::MessageParser<EwVerse> _parser = new pb::MessageParser<EwVerse>(() => new EwVerse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EwVerse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SeppoService.EwVerseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EwVerse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EwVerse(EwVerse other) : this() {
      verse_ = other.verse_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EwVerse Clone() {
      return new EwVerse(this);
    }

    /// <summary>Field number for the "verse" field.</summary>
    public const int VerseFieldNumber = 1;
    private string verse_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Verse {
      get { return verse_; }
      set {
        verse_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EwVerse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EwVerse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Verse != other.Verse) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Verse.Length != 0) hash ^= Verse.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Verse.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Verse);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Verse.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Verse);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EwVerse other) {
      if (other == null) {
        return;
      }
      if (other.Verse.Length != 0) {
        Verse = other.Verse;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Verse = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
