// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seppo_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SeppoService {

  /// <summary>Holder for reflection information generated from seppo_service.proto</summary>
  public static partial class SeppoServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for seppo_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SeppoServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNzZXBwb19zZXJ2aWNlLnByb3RvEgxTZXBwb1NlcnZpY2UaE3NvbmdfZGF0",
            "YWJhc2UucHJvdG8aHXNvbmdfZGF0YWJhc2VfdmFyaWF0aW9uLnByb3RvGhFl",
            "d19kYXRhYmFzZS5wcm90bxoNZXdfc29uZy5wcm90bxoOZXdfdmVyc2UucHJv",
            "dG8aD3ZhcmlhdGlvbi5wcm90bxoUdmFyaWF0aW9uX3RleHQucHJvdG8yyBMK",
            "BVNlcHBvEmkKEmZldGNoVmFyaWF0aW9uQnlJZBInLlNlcHBvU2VydmljZS5G",
            "ZXRjaFZhcmlhdGlvbkJ5SWRSZXF1ZXN0GiguU2VwcG9TZXJ2aWNlLkZldGNo",
            "VmFyaWF0aW9uQnlJZFJlc3BvbnNlIgASYwoQc2VhcmNoVmFyaWF0aW9ucxIl",
            "LlNlcHBvU2VydmljZS5TZWFyY2hWYXJpYXRpb25zUmVxdWVzdBomLlNlcHBv",
            "U2VydmljZS5TZWFyY2hWYXJpYXRpb25zUmVzcG9uc2UiABJfChZsaXN0ZW5G",
            "b3JDaGFuZ2VkRXdTb25nEisuU2VwcG9TZXJ2aWNlLkxpc3RlbkZvckNoYW5n",
            "ZWRFd1NvbmdSZXF1ZXN0GhQuU2VwcG9TZXJ2aWNlLkV3U29uZyIAMAESZgoS",
            "ZmV0Y2hTb25nRGF0YWJhc2VzEicuU2VwcG9TZXJ2aWNlLkZldGNoU29uZ0Rh",
            "dGFiYXNlc1JlcXVlc3QaJS5TZXBwb1NlcnZpY2UuU29uZ0RhdGFiYXNlc0Nv",
            "bm5lY3Rpb24iABJyChVmZXRjaFNvbmdEYXRhYmFzZUJ5SWQSKi5TZXBwb1Nl",
            "cnZpY2UuRmV0Y2hTb25nRGF0YWJhc2VCeUlkUmVxdWVzdBorLlNlcHBvU2Vy",
            "dmljZS5GZXRjaFNvbmdEYXRhYmFzZUJ5SWRSZXNwb25zZSIAEmAKEGZldGNo",
            "RXdEYXRhYmFzZXMSJS5TZXBwb1NlcnZpY2UuRmV0Y2hFd0RhdGFiYXNlc1Jl",
            "cXVlc3QaIy5TZXBwb1NlcnZpY2UuRXdEYXRhYmFzZXNDb25uZWN0aW9uIgAS",
            "bAoTZmV0Y2hFd0RhdGFiYXNlQnlJZBIoLlNlcHBvU2VydmljZS5GZXRjaEV3",
            "RGF0YWJhc2VCeUlkUmVxdWVzdBopLlNlcHBvU2VydmljZS5GZXRjaEV3RGF0",
            "YWJhc2VCeUlkUmVzcG9uc2UiABKQAQofZmV0Y2hWYXJpYXRpb25zQnlTb25n",
            "RGF0YWJhc2VJZBI0LlNlcHBvU2VydmljZS5GZXRjaFZhcmlhdGlvbnNCeVNv",
            "bmdEYXRhYmFzZUlkUmVxdWVzdBo1LlNlcHBvU2VydmljZS5GZXRjaFZhcmlh",
            "dGlvbnNCeVNvbmdEYXRhYmFzZUlkUmVzcG9uc2UiABKQAQofZmV0Y2hWYXJp",
            "YXRpb25UZXh0QnlWYXJpYXRpb25JZBI0LlNlcHBvU2VydmljZS5GZXRjaFZh",
            "cmlhdGlvblRleHRCeVZhcmlhdGlvbklkUmVxdWVzdBo1LlNlcHBvU2Vydmlj",
            "ZS5GZXRjaFZhcmlhdGlvblRleHRCeVZhcmlhdGlvbklkUmVzcG9uc2UiABJg",
            "Cg9jcmVhdGVWYXJpYXRpb24SJC5TZXBwb1NlcnZpY2UuQ3JlYXRlVmFyaWF0",
            "aW9uUmVxdWVzdBolLlNlcHBvU2VydmljZS5DcmVhdGVWYXJpYXRpb25SZXNw",
            "b25zZSIAEloKDWVkaXRWYXJpYXRpb24SIi5TZXBwb1NlcnZpY2UuRWRpdFZh",
            "cmlhdGlvblJlcXVlc3QaIy5TZXBwb1NlcnZpY2UuRWRpdFZhcmlhdGlvblJl",
            "c3BvbnNlIgASYAoPcmVtb3ZlVmFyaWF0aW9uEiQuU2VwcG9TZXJ2aWNlLlJl",
            "bW92ZVZhcmlhdGlvblJlcXVlc3QaJS5TZXBwb1NlcnZpY2UuUmVtb3ZlVmFy",
            "aWF0aW9uUmVzcG9uc2UiABJpChJjcmVhdGVTb25nRGF0YWJhc2USJy5TZXBw",
            "b1NlcnZpY2UuQ3JlYXRlU29uZ0RhdGFiYXNlUmVxdWVzdBooLlNlcHBvU2Vy",
            "dmljZS5DcmVhdGVTb25nRGF0YWJhc2VSZXNwb25zZSIAEmMKEGVkaXRTb25n",
            "RGF0YWJhc2USJS5TZXBwb1NlcnZpY2UuRWRpdFNvbmdEYXRhYmFzZVJlcXVl",
            "c3QaJi5TZXBwb1NlcnZpY2UuRWRpdFNvbmdEYXRhYmFzZVJlc3BvbnNlIgAS",
            "aQoScmVtb3ZlU29uZ0RhdGFiYXNlEicuU2VwcG9TZXJ2aWNlLlJlbW92ZVNv",
            "bmdEYXRhYmFzZVJlcXVlc3QaKC5TZXBwb1NlcnZpY2UuUmVtb3ZlU29uZ0Rh",
            "dGFiYXNlUmVzcG9uc2UiABJjChBjcmVhdGVFd0RhdGFiYXNlEiUuU2VwcG9T",
            "ZXJ2aWNlLkNyZWF0ZUV3RGF0YWJhc2VSZXF1ZXN0GiYuU2VwcG9TZXJ2aWNl",
            "LkNyZWF0ZUV3RGF0YWJhc2VSZXNwb25zZSIAEl0KDmVkaXRFd0RhdGFiYXNl",
            "EiMuU2VwcG9TZXJ2aWNlLkVkaXRFd0RhdGFiYXNlUmVxdWVzdBokLlNlcHBv",
            "U2VydmljZS5FZGl0RXdEYXRhYmFzZVJlc3BvbnNlIgASYwoQcmVtb3ZlRXdE",
            "YXRhYmFzZRIlLlNlcHBvU2VydmljZS5SZW1vdmVFd0RhdGFiYXNlUmVxdWVz",
            "dBomLlNlcHBvU2VydmljZS5SZW1vdmVFd0RhdGFiYXNlUmVzcG9uc2UiABKB",
            "AQoaYWRkVmFyaWF0aW9uVG9Tb25nRGF0YWJhc2USLy5TZXBwb1NlcnZpY2Uu",
            "QWRkVmFyaWF0aW9uVG9Tb25nRGF0YWJhc2VSZXF1ZXN0GjAuU2VwcG9TZXJ2",
            "aWNlLkFkZFZhcmlhdGlvblRvU29uZ0RhdGFiYXNlUmVzcG9uc2UiABKQAQof",
            "cmVtb3ZlVmFyaWF0aW9uRnJvbVNvbmdEYXRhYmFzZRI0LlNlcHBvU2Vydmlj",
            "ZS5SZW1vdmVWYXJpYXRpb25Gcm9tU29uZ0RhdGFiYXNlUmVxdWVzdBo1LlNl",
            "cHBvU2VydmljZS5SZW1vdmVWYXJpYXRpb25Gcm9tU29uZ0RhdGFiYXNlUmVz",
            "cG9uc2UiABJdCg5zeW5jRXdEYXRhYmFzZRIjLlNlcHBvU2VydmljZS5TeW5j",
            "RXdEYXRhYmFzZVJlcXVlc3QaJC5TZXBwb1NlcnZpY2UuU3luY0V3RGF0YWJh",
            "c2VSZXNwb25zZSIAEmAKD2luc2VydEV3U29uZ0lkcxIkLlNlcHBvU2Vydmlj",
            "ZS5JbnNlcnRFd1NvbmdJZHNSZXF1ZXN0GiUuU2VwcG9TZXJ2aWNlLkluc2Vy",
            "dEV3U29uZ0lkc1Jlc3BvbnNlIgASYAoPY2hhbmdlRXdTb25nSWRzEiQuU2Vw",
            "cG9TZXJ2aWNlLkNoYW5nZUV3U29uZ0lkc1JlcXVlc3QaJS5TZXBwb1NlcnZp",
            "Y2UuQ2hhbmdlRXdTb25nSWRzUmVzcG9uc2UiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SeppoService.SongDatabaseReflection.Descriptor, global::SeppoService.SongDatabaseVariationReflection.Descriptor, global::SeppoService.EwDatabaseReflection.Descriptor, global::SeppoService.EwSongReflection.Descriptor, global::SeppoService.EwVerseReflection.Descriptor, global::SeppoService.VariationReflection.Descriptor, global::SeppoService.VariationTextReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
