// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seppo_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SeppoService {

  /// <summary>Holder for reflection information generated from seppo_service.proto</summary>
  public static partial class SeppoServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for seppo_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SeppoServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNzZXBwb19zZXJ2aWNlLnByb3RvEgxTZXBwb1NlcnZpY2UaE3NvbmdfZGF0",
            "YWJhc2UucHJvdG8aHXNvbmdfZGF0YWJhc2VfdmFyaWF0aW9uLnByb3RvGhFl",
            "d19kYXRhYmFzZS5wcm90bxoNZXdfc29uZy5wcm90bxoOZXdfdmVyc2UucHJv",
            "dG8aD3ZhcmlhdGlvbi5wcm90bzLTEQoFU2VwcG8SaQoSZmV0Y2hWYXJpYXRp",
            "b25CeUlkEicuU2VwcG9TZXJ2aWNlLkZldGNoVmFyaWF0aW9uQnlJZFJlcXVl",
            "c3QaKC5TZXBwb1NlcnZpY2UuRmV0Y2hWYXJpYXRpb25CeUlkUmVzcG9uc2Ui",
            "ABJjChBzZWFyY2hWYXJpYXRpb25zEiUuU2VwcG9TZXJ2aWNlLlNlYXJjaFZh",
            "cmlhdGlvbnNSZXF1ZXN0GiYuU2VwcG9TZXJ2aWNlLlNlYXJjaFZhcmlhdGlv",
            "bnNSZXNwb25zZSIAEl8KFmxpc3RlbkZvckNoYW5nZWRFd1NvbmcSKy5TZXBw",
            "b1NlcnZpY2UuTGlzdGVuRm9yQ2hhbmdlZEV3U29uZ1JlcXVlc3QaFC5TZXBw",
            "b1NlcnZpY2UuRXdTb25nIgAwARJmChJmZXRjaFNvbmdEYXRhYmFzZXMSJy5T",
            "ZXBwb1NlcnZpY2UuRmV0Y2hTb25nRGF0YWJhc2VzUmVxdWVzdBolLlNlcHBv",
            "U2VydmljZS5Tb25nRGF0YWJhc2VzQ29ubmVjdGlvbiIAEnIKFWZldGNoU29u",
            "Z0RhdGFiYXNlQnlJZBIqLlNlcHBvU2VydmljZS5GZXRjaFNvbmdEYXRhYmFz",
            "ZUJ5SWRSZXF1ZXN0GisuU2VwcG9TZXJ2aWNlLkZldGNoU29uZ0RhdGFiYXNl",
            "QnlJZFJlc3BvbnNlIgASYAoQZmV0Y2hFd0RhdGFiYXNlcxIlLlNlcHBvU2Vy",
            "dmljZS5GZXRjaEV3RGF0YWJhc2VzUmVxdWVzdBojLlNlcHBvU2VydmljZS5F",
            "d0RhdGFiYXNlc0Nvbm5lY3Rpb24iABJsChNmZXRjaEV3RGF0YWJhc2VCeUlk",
            "EiguU2VwcG9TZXJ2aWNlLkZldGNoRXdEYXRhYmFzZUJ5SWRSZXF1ZXN0Giku",
            "U2VwcG9TZXJ2aWNlLkZldGNoRXdEYXRhYmFzZUJ5SWRSZXNwb25zZSIAEpAB",
            "Ch9mZXRjaFZhcmlhdGlvbnNCeVNvbmdEYXRhYmFzZUlkEjQuU2VwcG9TZXJ2",
            "aWNlLkZldGNoVmFyaWF0aW9uc0J5U29uZ0RhdGFiYXNlSWRSZXF1ZXN0GjUu",
            "U2VwcG9TZXJ2aWNlLkZldGNoVmFyaWF0aW9uc0J5U29uZ0RhdGFiYXNlSWRS",
            "ZXNwb25zZSIAEmAKD2NyZWF0ZVZhcmlhdGlvbhIkLlNlcHBvU2VydmljZS5D",
            "cmVhdGVWYXJpYXRpb25SZXF1ZXN0GiUuU2VwcG9TZXJ2aWNlLkNyZWF0ZVZh",
            "cmlhdGlvblJlc3BvbnNlIgASWgoNZWRpdFZhcmlhdGlvbhIiLlNlcHBvU2Vy",
            "dmljZS5FZGl0VmFyaWF0aW9uUmVxdWVzdBojLlNlcHBvU2VydmljZS5FZGl0",
            "VmFyaWF0aW9uUmVzcG9uc2UiABJgCg9yZW1vdmVWYXJpYXRpb24SJC5TZXBw",
            "b1NlcnZpY2UuUmVtb3ZlVmFyaWF0aW9uUmVxdWVzdBolLlNlcHBvU2Vydmlj",
            "ZS5SZW1vdmVWYXJpYXRpb25SZXNwb25zZSIAEmkKEmNyZWF0ZVNvbmdEYXRh",
            "YmFzZRInLlNlcHBvU2VydmljZS5DcmVhdGVTb25nRGF0YWJhc2VSZXF1ZXN0",
            "GiguU2VwcG9TZXJ2aWNlLkNyZWF0ZVNvbmdEYXRhYmFzZVJlc3BvbnNlIgAS",
            "YwoQZWRpdFNvbmdEYXRhYmFzZRIlLlNlcHBvU2VydmljZS5FZGl0U29uZ0Rh",
            "dGFiYXNlUmVxdWVzdBomLlNlcHBvU2VydmljZS5FZGl0U29uZ0RhdGFiYXNl",
            "UmVzcG9uc2UiABJpChJyZW1vdmVTb25nRGF0YWJhc2USJy5TZXBwb1NlcnZp",
            "Y2UuUmVtb3ZlU29uZ0RhdGFiYXNlUmVxdWVzdBooLlNlcHBvU2VydmljZS5S",
            "ZW1vdmVTb25nRGF0YWJhc2VSZXNwb25zZSIAEmMKEGNyZWF0ZUV3RGF0YWJh",
            "c2USJS5TZXBwb1NlcnZpY2UuQ3JlYXRlRXdEYXRhYmFzZVJlcXVlc3QaJi5T",
            "ZXBwb1NlcnZpY2UuQ3JlYXRlRXdEYXRhYmFzZVJlc3BvbnNlIgASXQoOZWRp",
            "dEV3RGF0YWJhc2USIy5TZXBwb1NlcnZpY2UuRWRpdEV3RGF0YWJhc2VSZXF1",
            "ZXN0GiQuU2VwcG9TZXJ2aWNlLkVkaXRFd0RhdGFiYXNlUmVzcG9uc2UiABJj",
            "ChByZW1vdmVFd0RhdGFiYXNlEiUuU2VwcG9TZXJ2aWNlLlJlbW92ZUV3RGF0",
            "YWJhc2VSZXF1ZXN0GiYuU2VwcG9TZXJ2aWNlLlJlbW92ZUV3RGF0YWJhc2VS",
            "ZXNwb25zZSIAEoEBChphZGRWYXJpYXRpb25Ub1NvbmdEYXRhYmFzZRIvLlNl",
            "cHBvU2VydmljZS5BZGRWYXJpYXRpb25Ub1NvbmdEYXRhYmFzZVJlcXVlc3Qa",
            "MC5TZXBwb1NlcnZpY2UuQWRkVmFyaWF0aW9uVG9Tb25nRGF0YWJhc2VSZXNw",
            "b25zZSIAEpABCh9yZW1vdmVWYXJpYXRpb25Gcm9tU29uZ0RhdGFiYXNlEjQu",
            "U2VwcG9TZXJ2aWNlLlJlbW92ZVZhcmlhdGlvbkZyb21Tb25nRGF0YWJhc2VS",
            "ZXF1ZXN0GjUuU2VwcG9TZXJ2aWNlLlJlbW92ZVZhcmlhdGlvbkZyb21Tb25n",
            "RGF0YWJhc2VSZXNwb25zZSIAEl0KDnN5bmNFd0RhdGFiYXNlEiMuU2VwcG9T",
            "ZXJ2aWNlLlN5bmNFd0RhdGFiYXNlUmVxdWVzdBokLlNlcHBvU2VydmljZS5T",
            "eW5jRXdEYXRhYmFzZVJlc3BvbnNlIgASYAoPaW5zZXJ0RXdTb25nSWRzEiQu",
            "U2VwcG9TZXJ2aWNlLkluc2VydEV3U29uZ0lkc1JlcXVlc3QaJS5TZXBwb1Nl",
            "cnZpY2UuSW5zZXJ0RXdTb25nSWRzUmVzcG9uc2UiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SeppoService.SongDatabaseReflection.Descriptor, global::SeppoService.SongDatabaseVariationReflection.Descriptor, global::SeppoService.EwDatabaseReflection.Descriptor, global::SeppoService.EwSongReflection.Descriptor, global::SeppoService.EwVerseReflection.Descriptor, global::SeppoService.VariationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
