// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seppo_service.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace SeppoService {
  /// <summary>
  /// Queries
  /// </summary>
  public static partial class Seppo
  {
    static readonly string __ServiceName = "SeppoService.Seppo";

    static readonly grpc::Marshaller<global::SeppoService.FetchVariationByIdRequest> __Marshaller_FetchVariationByIdRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.FetchVariationByIdRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.FetchVariationByIdResponse> __Marshaller_FetchVariationByIdResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.FetchVariationByIdResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.SearchVariationsRequest> __Marshaller_SearchVariationsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.SearchVariationsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.SearchVariationsResponse> __Marshaller_SearchVariationsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.SearchVariationsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.ListenForChangedEwSongRequest> __Marshaller_ListenForChangedEwSongRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.ListenForChangedEwSongRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.EwSong> __Marshaller_EwSong = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.EwSong.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.FetchSongDatabasesRequest> __Marshaller_FetchSongDatabasesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.FetchSongDatabasesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.SongDatabasesConnection> __Marshaller_SongDatabasesConnection = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.SongDatabasesConnection.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.FetchSongDatabaseByIdRequest> __Marshaller_FetchSongDatabaseByIdRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.FetchSongDatabaseByIdRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.FetchSongDatabaseByIdResponse> __Marshaller_FetchSongDatabaseByIdResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.FetchSongDatabaseByIdResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.FetchEwDatabasesRequest> __Marshaller_FetchEwDatabasesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.FetchEwDatabasesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.EwDatabasesConnection> __Marshaller_EwDatabasesConnection = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.EwDatabasesConnection.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.FetchEwDatabaseByIdRequest> __Marshaller_FetchEwDatabaseByIdRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.FetchEwDatabaseByIdRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.FetchEwDatabaseByIdResponse> __Marshaller_FetchEwDatabaseByIdResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.FetchEwDatabaseByIdResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.FetchVariationsBySongDatabaseIdRequest> __Marshaller_FetchVariationsBySongDatabaseIdRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.FetchVariationsBySongDatabaseIdRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.FetchVariationsBySongDatabaseIdResponse> __Marshaller_FetchVariationsBySongDatabaseIdResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.FetchVariationsBySongDatabaseIdResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.CreateVariationRequest> __Marshaller_CreateVariationRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.CreateVariationRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.CreateVariationResponse> __Marshaller_CreateVariationResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.CreateVariationResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.EditVariationRequest> __Marshaller_EditVariationRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.EditVariationRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.EditVariationResponse> __Marshaller_EditVariationResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.EditVariationResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.RemoveVariationRequest> __Marshaller_RemoveVariationRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.RemoveVariationRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.RemoveVariationResponse> __Marshaller_RemoveVariationResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.RemoveVariationResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.CreateSongDatabaseRequest> __Marshaller_CreateSongDatabaseRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.CreateSongDatabaseRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.CreateSongDatabaseResponse> __Marshaller_CreateSongDatabaseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.CreateSongDatabaseResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.EditSongDatabaseRequest> __Marshaller_EditSongDatabaseRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.EditSongDatabaseRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.EditSongDatabaseResponse> __Marshaller_EditSongDatabaseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.EditSongDatabaseResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.RemoveSongDatabaseRequest> __Marshaller_RemoveSongDatabaseRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.RemoveSongDatabaseRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.RemoveSongDatabaseResponse> __Marshaller_RemoveSongDatabaseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.RemoveSongDatabaseResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.CreateEwDatabaseRequest> __Marshaller_CreateEwDatabaseRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.CreateEwDatabaseRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.CreateEwDatabaseResponse> __Marshaller_CreateEwDatabaseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.CreateEwDatabaseResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.EditEwDatabaseRequest> __Marshaller_EditEwDatabaseRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.EditEwDatabaseRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.EditEwDatabaseResponse> __Marshaller_EditEwDatabaseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.EditEwDatabaseResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.RemoveEwDatabaseRequest> __Marshaller_RemoveEwDatabaseRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.RemoveEwDatabaseRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.RemoveEwDatabaseResponse> __Marshaller_RemoveEwDatabaseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.RemoveEwDatabaseResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.AddVariationToSongDatabaseRequest> __Marshaller_AddVariationToSongDatabaseRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.AddVariationToSongDatabaseRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.AddVariationToSongDatabaseResponse> __Marshaller_AddVariationToSongDatabaseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.AddVariationToSongDatabaseResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.RemoveVariationFromSongDatabaseRequest> __Marshaller_RemoveVariationFromSongDatabaseRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.RemoveVariationFromSongDatabaseRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.RemoveVariationFromSongDatabaseResponse> __Marshaller_RemoveVariationFromSongDatabaseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.RemoveVariationFromSongDatabaseResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.SyncEwDatabaseRequest> __Marshaller_SyncEwDatabaseRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.SyncEwDatabaseRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.SyncEwDatabaseResponse> __Marshaller_SyncEwDatabaseResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.SyncEwDatabaseResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.InsertEwSongIdsRequest> __Marshaller_InsertEwSongIdsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.InsertEwSongIdsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SeppoService.InsertEwSongIdsResponse> __Marshaller_InsertEwSongIdsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SeppoService.InsertEwSongIdsResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::SeppoService.FetchVariationByIdRequest, global::SeppoService.FetchVariationByIdResponse> __Method_fetchVariationById = new grpc::Method<global::SeppoService.FetchVariationByIdRequest, global::SeppoService.FetchVariationByIdResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "fetchVariationById",
        __Marshaller_FetchVariationByIdRequest,
        __Marshaller_FetchVariationByIdResponse);

    static readonly grpc::Method<global::SeppoService.SearchVariationsRequest, global::SeppoService.SearchVariationsResponse> __Method_searchVariations = new grpc::Method<global::SeppoService.SearchVariationsRequest, global::SeppoService.SearchVariationsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "searchVariations",
        __Marshaller_SearchVariationsRequest,
        __Marshaller_SearchVariationsResponse);

    static readonly grpc::Method<global::SeppoService.ListenForChangedEwSongRequest, global::SeppoService.EwSong> __Method_listenForChangedEwSong = new grpc::Method<global::SeppoService.ListenForChangedEwSongRequest, global::SeppoService.EwSong>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "listenForChangedEwSong",
        __Marshaller_ListenForChangedEwSongRequest,
        __Marshaller_EwSong);

    static readonly grpc::Method<global::SeppoService.FetchSongDatabasesRequest, global::SeppoService.SongDatabasesConnection> __Method_fetchSongDatabases = new grpc::Method<global::SeppoService.FetchSongDatabasesRequest, global::SeppoService.SongDatabasesConnection>(
        grpc::MethodType.Unary,
        __ServiceName,
        "fetchSongDatabases",
        __Marshaller_FetchSongDatabasesRequest,
        __Marshaller_SongDatabasesConnection);

    static readonly grpc::Method<global::SeppoService.FetchSongDatabaseByIdRequest, global::SeppoService.FetchSongDatabaseByIdResponse> __Method_fetchSongDatabaseById = new grpc::Method<global::SeppoService.FetchSongDatabaseByIdRequest, global::SeppoService.FetchSongDatabaseByIdResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "fetchSongDatabaseById",
        __Marshaller_FetchSongDatabaseByIdRequest,
        __Marshaller_FetchSongDatabaseByIdResponse);

    static readonly grpc::Method<global::SeppoService.FetchEwDatabasesRequest, global::SeppoService.EwDatabasesConnection> __Method_fetchEwDatabases = new grpc::Method<global::SeppoService.FetchEwDatabasesRequest, global::SeppoService.EwDatabasesConnection>(
        grpc::MethodType.Unary,
        __ServiceName,
        "fetchEwDatabases",
        __Marshaller_FetchEwDatabasesRequest,
        __Marshaller_EwDatabasesConnection);

    static readonly grpc::Method<global::SeppoService.FetchEwDatabaseByIdRequest, global::SeppoService.FetchEwDatabaseByIdResponse> __Method_fetchEwDatabaseById = new grpc::Method<global::SeppoService.FetchEwDatabaseByIdRequest, global::SeppoService.FetchEwDatabaseByIdResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "fetchEwDatabaseById",
        __Marshaller_FetchEwDatabaseByIdRequest,
        __Marshaller_FetchEwDatabaseByIdResponse);

    static readonly grpc::Method<global::SeppoService.FetchVariationsBySongDatabaseIdRequest, global::SeppoService.FetchVariationsBySongDatabaseIdResponse> __Method_fetchVariationsBySongDatabaseId = new grpc::Method<global::SeppoService.FetchVariationsBySongDatabaseIdRequest, global::SeppoService.FetchVariationsBySongDatabaseIdResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "fetchVariationsBySongDatabaseId",
        __Marshaller_FetchVariationsBySongDatabaseIdRequest,
        __Marshaller_FetchVariationsBySongDatabaseIdResponse);

    static readonly grpc::Method<global::SeppoService.CreateVariationRequest, global::SeppoService.CreateVariationResponse> __Method_createVariation = new grpc::Method<global::SeppoService.CreateVariationRequest, global::SeppoService.CreateVariationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "createVariation",
        __Marshaller_CreateVariationRequest,
        __Marshaller_CreateVariationResponse);

    static readonly grpc::Method<global::SeppoService.EditVariationRequest, global::SeppoService.EditVariationResponse> __Method_editVariation = new grpc::Method<global::SeppoService.EditVariationRequest, global::SeppoService.EditVariationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "editVariation",
        __Marshaller_EditVariationRequest,
        __Marshaller_EditVariationResponse);

    static readonly grpc::Method<global::SeppoService.RemoveVariationRequest, global::SeppoService.RemoveVariationResponse> __Method_removeVariation = new grpc::Method<global::SeppoService.RemoveVariationRequest, global::SeppoService.RemoveVariationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "removeVariation",
        __Marshaller_RemoveVariationRequest,
        __Marshaller_RemoveVariationResponse);

    static readonly grpc::Method<global::SeppoService.CreateSongDatabaseRequest, global::SeppoService.CreateSongDatabaseResponse> __Method_createSongDatabase = new grpc::Method<global::SeppoService.CreateSongDatabaseRequest, global::SeppoService.CreateSongDatabaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "createSongDatabase",
        __Marshaller_CreateSongDatabaseRequest,
        __Marshaller_CreateSongDatabaseResponse);

    static readonly grpc::Method<global::SeppoService.EditSongDatabaseRequest, global::SeppoService.EditSongDatabaseResponse> __Method_editSongDatabase = new grpc::Method<global::SeppoService.EditSongDatabaseRequest, global::SeppoService.EditSongDatabaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "editSongDatabase",
        __Marshaller_EditSongDatabaseRequest,
        __Marshaller_EditSongDatabaseResponse);

    static readonly grpc::Method<global::SeppoService.RemoveSongDatabaseRequest, global::SeppoService.RemoveSongDatabaseResponse> __Method_removeSongDatabase = new grpc::Method<global::SeppoService.RemoveSongDatabaseRequest, global::SeppoService.RemoveSongDatabaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "removeSongDatabase",
        __Marshaller_RemoveSongDatabaseRequest,
        __Marshaller_RemoveSongDatabaseResponse);

    static readonly grpc::Method<global::SeppoService.CreateEwDatabaseRequest, global::SeppoService.CreateEwDatabaseResponse> __Method_createEwDatabase = new grpc::Method<global::SeppoService.CreateEwDatabaseRequest, global::SeppoService.CreateEwDatabaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "createEwDatabase",
        __Marshaller_CreateEwDatabaseRequest,
        __Marshaller_CreateEwDatabaseResponse);

    static readonly grpc::Method<global::SeppoService.EditEwDatabaseRequest, global::SeppoService.EditEwDatabaseResponse> __Method_editEwDatabase = new grpc::Method<global::SeppoService.EditEwDatabaseRequest, global::SeppoService.EditEwDatabaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "editEwDatabase",
        __Marshaller_EditEwDatabaseRequest,
        __Marshaller_EditEwDatabaseResponse);

    static readonly grpc::Method<global::SeppoService.RemoveEwDatabaseRequest, global::SeppoService.RemoveEwDatabaseResponse> __Method_removeEwDatabase = new grpc::Method<global::SeppoService.RemoveEwDatabaseRequest, global::SeppoService.RemoveEwDatabaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "removeEwDatabase",
        __Marshaller_RemoveEwDatabaseRequest,
        __Marshaller_RemoveEwDatabaseResponse);

    static readonly grpc::Method<global::SeppoService.AddVariationToSongDatabaseRequest, global::SeppoService.AddVariationToSongDatabaseResponse> __Method_addVariationToSongDatabase = new grpc::Method<global::SeppoService.AddVariationToSongDatabaseRequest, global::SeppoService.AddVariationToSongDatabaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "addVariationToSongDatabase",
        __Marshaller_AddVariationToSongDatabaseRequest,
        __Marshaller_AddVariationToSongDatabaseResponse);

    static readonly grpc::Method<global::SeppoService.RemoveVariationFromSongDatabaseRequest, global::SeppoService.RemoveVariationFromSongDatabaseResponse> __Method_removeVariationFromSongDatabase = new grpc::Method<global::SeppoService.RemoveVariationFromSongDatabaseRequest, global::SeppoService.RemoveVariationFromSongDatabaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "removeVariationFromSongDatabase",
        __Marshaller_RemoveVariationFromSongDatabaseRequest,
        __Marshaller_RemoveVariationFromSongDatabaseResponse);

    static readonly grpc::Method<global::SeppoService.SyncEwDatabaseRequest, global::SeppoService.SyncEwDatabaseResponse> __Method_syncEwDatabase = new grpc::Method<global::SeppoService.SyncEwDatabaseRequest, global::SeppoService.SyncEwDatabaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "syncEwDatabase",
        __Marshaller_SyncEwDatabaseRequest,
        __Marshaller_SyncEwDatabaseResponse);

    static readonly grpc::Method<global::SeppoService.InsertEwSongIdsRequest, global::SeppoService.InsertEwSongIdsResponse> __Method_insertEwSongIds = new grpc::Method<global::SeppoService.InsertEwSongIdsRequest, global::SeppoService.InsertEwSongIdsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "insertEwSongIds",
        __Marshaller_InsertEwSongIdsRequest,
        __Marshaller_InsertEwSongIdsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SeppoService.SeppoServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Seppo</summary>
    public abstract partial class SeppoBase
    {
      public virtual global::System.Threading.Tasks.Task<global::SeppoService.FetchVariationByIdResponse> fetchVariationById(global::SeppoService.FetchVariationByIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.SearchVariationsResponse> searchVariations(global::SeppoService.SearchVariationsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task listenForChangedEwSong(global::SeppoService.ListenForChangedEwSongRequest request, grpc::IServerStreamWriter<global::SeppoService.EwSong> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.SongDatabasesConnection> fetchSongDatabases(global::SeppoService.FetchSongDatabasesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.FetchSongDatabaseByIdResponse> fetchSongDatabaseById(global::SeppoService.FetchSongDatabaseByIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.EwDatabasesConnection> fetchEwDatabases(global::SeppoService.FetchEwDatabasesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.FetchEwDatabaseByIdResponse> fetchEwDatabaseById(global::SeppoService.FetchEwDatabaseByIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.FetchVariationsBySongDatabaseIdResponse> fetchVariationsBySongDatabaseId(global::SeppoService.FetchVariationsBySongDatabaseIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.CreateVariationResponse> createVariation(global::SeppoService.CreateVariationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.EditVariationResponse> editVariation(global::SeppoService.EditVariationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.RemoveVariationResponse> removeVariation(global::SeppoService.RemoveVariationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.CreateSongDatabaseResponse> createSongDatabase(global::SeppoService.CreateSongDatabaseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.EditSongDatabaseResponse> editSongDatabase(global::SeppoService.EditSongDatabaseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.RemoveSongDatabaseResponse> removeSongDatabase(global::SeppoService.RemoveSongDatabaseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.CreateEwDatabaseResponse> createEwDatabase(global::SeppoService.CreateEwDatabaseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.EditEwDatabaseResponse> editEwDatabase(global::SeppoService.EditEwDatabaseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.RemoveEwDatabaseResponse> removeEwDatabase(global::SeppoService.RemoveEwDatabaseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.AddVariationToSongDatabaseResponse> addVariationToSongDatabase(global::SeppoService.AddVariationToSongDatabaseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.RemoveVariationFromSongDatabaseResponse> removeVariationFromSongDatabase(global::SeppoService.RemoveVariationFromSongDatabaseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.SyncEwDatabaseResponse> syncEwDatabase(global::SeppoService.SyncEwDatabaseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SeppoService.InsertEwSongIdsResponse> insertEwSongIds(global::SeppoService.InsertEwSongIdsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Seppo</summary>
    public partial class SeppoClient : grpc::ClientBase<SeppoClient>
    {
      /// <summary>Creates a new client for Seppo</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SeppoClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Seppo that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SeppoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SeppoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SeppoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::SeppoService.FetchVariationByIdResponse fetchVariationById(global::SeppoService.FetchVariationByIdRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchVariationById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.FetchVariationByIdResponse fetchVariationById(global::SeppoService.FetchVariationByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_fetchVariationById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.FetchVariationByIdResponse> fetchVariationByIdAsync(global::SeppoService.FetchVariationByIdRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchVariationByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.FetchVariationByIdResponse> fetchVariationByIdAsync(global::SeppoService.FetchVariationByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_fetchVariationById, null, options, request);
      }
      public virtual global::SeppoService.SearchVariationsResponse searchVariations(global::SeppoService.SearchVariationsRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return searchVariations(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.SearchVariationsResponse searchVariations(global::SeppoService.SearchVariationsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_searchVariations, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.SearchVariationsResponse> searchVariationsAsync(global::SeppoService.SearchVariationsRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return searchVariationsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.SearchVariationsResponse> searchVariationsAsync(global::SeppoService.SearchVariationsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_searchVariations, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::SeppoService.EwSong> listenForChangedEwSong(global::SeppoService.ListenForChangedEwSongRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return listenForChangedEwSong(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::SeppoService.EwSong> listenForChangedEwSong(global::SeppoService.ListenForChangedEwSongRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_listenForChangedEwSong, null, options, request);
      }
      public virtual global::SeppoService.SongDatabasesConnection fetchSongDatabases(global::SeppoService.FetchSongDatabasesRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchSongDatabases(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.SongDatabasesConnection fetchSongDatabases(global::SeppoService.FetchSongDatabasesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_fetchSongDatabases, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.SongDatabasesConnection> fetchSongDatabasesAsync(global::SeppoService.FetchSongDatabasesRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchSongDatabasesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.SongDatabasesConnection> fetchSongDatabasesAsync(global::SeppoService.FetchSongDatabasesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_fetchSongDatabases, null, options, request);
      }
      public virtual global::SeppoService.FetchSongDatabaseByIdResponse fetchSongDatabaseById(global::SeppoService.FetchSongDatabaseByIdRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchSongDatabaseById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.FetchSongDatabaseByIdResponse fetchSongDatabaseById(global::SeppoService.FetchSongDatabaseByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_fetchSongDatabaseById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.FetchSongDatabaseByIdResponse> fetchSongDatabaseByIdAsync(global::SeppoService.FetchSongDatabaseByIdRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchSongDatabaseByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.FetchSongDatabaseByIdResponse> fetchSongDatabaseByIdAsync(global::SeppoService.FetchSongDatabaseByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_fetchSongDatabaseById, null, options, request);
      }
      public virtual global::SeppoService.EwDatabasesConnection fetchEwDatabases(global::SeppoService.FetchEwDatabasesRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchEwDatabases(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.EwDatabasesConnection fetchEwDatabases(global::SeppoService.FetchEwDatabasesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_fetchEwDatabases, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.EwDatabasesConnection> fetchEwDatabasesAsync(global::SeppoService.FetchEwDatabasesRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchEwDatabasesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.EwDatabasesConnection> fetchEwDatabasesAsync(global::SeppoService.FetchEwDatabasesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_fetchEwDatabases, null, options, request);
      }
      public virtual global::SeppoService.FetchEwDatabaseByIdResponse fetchEwDatabaseById(global::SeppoService.FetchEwDatabaseByIdRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchEwDatabaseById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.FetchEwDatabaseByIdResponse fetchEwDatabaseById(global::SeppoService.FetchEwDatabaseByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_fetchEwDatabaseById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.FetchEwDatabaseByIdResponse> fetchEwDatabaseByIdAsync(global::SeppoService.FetchEwDatabaseByIdRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchEwDatabaseByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.FetchEwDatabaseByIdResponse> fetchEwDatabaseByIdAsync(global::SeppoService.FetchEwDatabaseByIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_fetchEwDatabaseById, null, options, request);
      }
      public virtual global::SeppoService.FetchVariationsBySongDatabaseIdResponse fetchVariationsBySongDatabaseId(global::SeppoService.FetchVariationsBySongDatabaseIdRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchVariationsBySongDatabaseId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.FetchVariationsBySongDatabaseIdResponse fetchVariationsBySongDatabaseId(global::SeppoService.FetchVariationsBySongDatabaseIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_fetchVariationsBySongDatabaseId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.FetchVariationsBySongDatabaseIdResponse> fetchVariationsBySongDatabaseIdAsync(global::SeppoService.FetchVariationsBySongDatabaseIdRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return fetchVariationsBySongDatabaseIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.FetchVariationsBySongDatabaseIdResponse> fetchVariationsBySongDatabaseIdAsync(global::SeppoService.FetchVariationsBySongDatabaseIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_fetchVariationsBySongDatabaseId, null, options, request);
      }
      public virtual global::SeppoService.CreateVariationResponse createVariation(global::SeppoService.CreateVariationRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return createVariation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.CreateVariationResponse createVariation(global::SeppoService.CreateVariationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_createVariation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.CreateVariationResponse> createVariationAsync(global::SeppoService.CreateVariationRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return createVariationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.CreateVariationResponse> createVariationAsync(global::SeppoService.CreateVariationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_createVariation, null, options, request);
      }
      public virtual global::SeppoService.EditVariationResponse editVariation(global::SeppoService.EditVariationRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return editVariation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.EditVariationResponse editVariation(global::SeppoService.EditVariationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_editVariation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.EditVariationResponse> editVariationAsync(global::SeppoService.EditVariationRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return editVariationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.EditVariationResponse> editVariationAsync(global::SeppoService.EditVariationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_editVariation, null, options, request);
      }
      public virtual global::SeppoService.RemoveVariationResponse removeVariation(global::SeppoService.RemoveVariationRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return removeVariation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.RemoveVariationResponse removeVariation(global::SeppoService.RemoveVariationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_removeVariation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.RemoveVariationResponse> removeVariationAsync(global::SeppoService.RemoveVariationRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return removeVariationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.RemoveVariationResponse> removeVariationAsync(global::SeppoService.RemoveVariationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_removeVariation, null, options, request);
      }
      public virtual global::SeppoService.CreateSongDatabaseResponse createSongDatabase(global::SeppoService.CreateSongDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return createSongDatabase(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.CreateSongDatabaseResponse createSongDatabase(global::SeppoService.CreateSongDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_createSongDatabase, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.CreateSongDatabaseResponse> createSongDatabaseAsync(global::SeppoService.CreateSongDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return createSongDatabaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.CreateSongDatabaseResponse> createSongDatabaseAsync(global::SeppoService.CreateSongDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_createSongDatabase, null, options, request);
      }
      public virtual global::SeppoService.EditSongDatabaseResponse editSongDatabase(global::SeppoService.EditSongDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return editSongDatabase(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.EditSongDatabaseResponse editSongDatabase(global::SeppoService.EditSongDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_editSongDatabase, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.EditSongDatabaseResponse> editSongDatabaseAsync(global::SeppoService.EditSongDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return editSongDatabaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.EditSongDatabaseResponse> editSongDatabaseAsync(global::SeppoService.EditSongDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_editSongDatabase, null, options, request);
      }
      public virtual global::SeppoService.RemoveSongDatabaseResponse removeSongDatabase(global::SeppoService.RemoveSongDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return removeSongDatabase(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.RemoveSongDatabaseResponse removeSongDatabase(global::SeppoService.RemoveSongDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_removeSongDatabase, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.RemoveSongDatabaseResponse> removeSongDatabaseAsync(global::SeppoService.RemoveSongDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return removeSongDatabaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.RemoveSongDatabaseResponse> removeSongDatabaseAsync(global::SeppoService.RemoveSongDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_removeSongDatabase, null, options, request);
      }
      public virtual global::SeppoService.CreateEwDatabaseResponse createEwDatabase(global::SeppoService.CreateEwDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return createEwDatabase(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.CreateEwDatabaseResponse createEwDatabase(global::SeppoService.CreateEwDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_createEwDatabase, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.CreateEwDatabaseResponse> createEwDatabaseAsync(global::SeppoService.CreateEwDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return createEwDatabaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.CreateEwDatabaseResponse> createEwDatabaseAsync(global::SeppoService.CreateEwDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_createEwDatabase, null, options, request);
      }
      public virtual global::SeppoService.EditEwDatabaseResponse editEwDatabase(global::SeppoService.EditEwDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return editEwDatabase(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.EditEwDatabaseResponse editEwDatabase(global::SeppoService.EditEwDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_editEwDatabase, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.EditEwDatabaseResponse> editEwDatabaseAsync(global::SeppoService.EditEwDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return editEwDatabaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.EditEwDatabaseResponse> editEwDatabaseAsync(global::SeppoService.EditEwDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_editEwDatabase, null, options, request);
      }
      public virtual global::SeppoService.RemoveEwDatabaseResponse removeEwDatabase(global::SeppoService.RemoveEwDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return removeEwDatabase(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.RemoveEwDatabaseResponse removeEwDatabase(global::SeppoService.RemoveEwDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_removeEwDatabase, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.RemoveEwDatabaseResponse> removeEwDatabaseAsync(global::SeppoService.RemoveEwDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return removeEwDatabaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.RemoveEwDatabaseResponse> removeEwDatabaseAsync(global::SeppoService.RemoveEwDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_removeEwDatabase, null, options, request);
      }
      public virtual global::SeppoService.AddVariationToSongDatabaseResponse addVariationToSongDatabase(global::SeppoService.AddVariationToSongDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return addVariationToSongDatabase(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.AddVariationToSongDatabaseResponse addVariationToSongDatabase(global::SeppoService.AddVariationToSongDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_addVariationToSongDatabase, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.AddVariationToSongDatabaseResponse> addVariationToSongDatabaseAsync(global::SeppoService.AddVariationToSongDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return addVariationToSongDatabaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.AddVariationToSongDatabaseResponse> addVariationToSongDatabaseAsync(global::SeppoService.AddVariationToSongDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_addVariationToSongDatabase, null, options, request);
      }
      public virtual global::SeppoService.RemoveVariationFromSongDatabaseResponse removeVariationFromSongDatabase(global::SeppoService.RemoveVariationFromSongDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return removeVariationFromSongDatabase(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.RemoveVariationFromSongDatabaseResponse removeVariationFromSongDatabase(global::SeppoService.RemoveVariationFromSongDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_removeVariationFromSongDatabase, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.RemoveVariationFromSongDatabaseResponse> removeVariationFromSongDatabaseAsync(global::SeppoService.RemoveVariationFromSongDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return removeVariationFromSongDatabaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.RemoveVariationFromSongDatabaseResponse> removeVariationFromSongDatabaseAsync(global::SeppoService.RemoveVariationFromSongDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_removeVariationFromSongDatabase, null, options, request);
      }
      public virtual global::SeppoService.SyncEwDatabaseResponse syncEwDatabase(global::SeppoService.SyncEwDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return syncEwDatabase(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.SyncEwDatabaseResponse syncEwDatabase(global::SeppoService.SyncEwDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_syncEwDatabase, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.SyncEwDatabaseResponse> syncEwDatabaseAsync(global::SeppoService.SyncEwDatabaseRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return syncEwDatabaseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.SyncEwDatabaseResponse> syncEwDatabaseAsync(global::SeppoService.SyncEwDatabaseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_syncEwDatabase, null, options, request);
      }
      public virtual global::SeppoService.InsertEwSongIdsResponse insertEwSongIds(global::SeppoService.InsertEwSongIdsRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return insertEwSongIds(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SeppoService.InsertEwSongIdsResponse insertEwSongIds(global::SeppoService.InsertEwSongIdsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_insertEwSongIds, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.InsertEwSongIdsResponse> insertEwSongIdsAsync(global::SeppoService.InsertEwSongIdsRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return insertEwSongIdsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SeppoService.InsertEwSongIdsResponse> insertEwSongIdsAsync(global::SeppoService.InsertEwSongIdsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_insertEwSongIds, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SeppoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SeppoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SeppoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_fetchVariationById, serviceImpl.fetchVariationById)
          .AddMethod(__Method_searchVariations, serviceImpl.searchVariations)
          .AddMethod(__Method_listenForChangedEwSong, serviceImpl.listenForChangedEwSong)
          .AddMethod(__Method_fetchSongDatabases, serviceImpl.fetchSongDatabases)
          .AddMethod(__Method_fetchSongDatabaseById, serviceImpl.fetchSongDatabaseById)
          .AddMethod(__Method_fetchEwDatabases, serviceImpl.fetchEwDatabases)
          .AddMethod(__Method_fetchEwDatabaseById, serviceImpl.fetchEwDatabaseById)
          .AddMethod(__Method_fetchVariationsBySongDatabaseId, serviceImpl.fetchVariationsBySongDatabaseId)
          .AddMethod(__Method_createVariation, serviceImpl.createVariation)
          .AddMethod(__Method_editVariation, serviceImpl.editVariation)
          .AddMethod(__Method_removeVariation, serviceImpl.removeVariation)
          .AddMethod(__Method_createSongDatabase, serviceImpl.createSongDatabase)
          .AddMethod(__Method_editSongDatabase, serviceImpl.editSongDatabase)
          .AddMethod(__Method_removeSongDatabase, serviceImpl.removeSongDatabase)
          .AddMethod(__Method_createEwDatabase, serviceImpl.createEwDatabase)
          .AddMethod(__Method_editEwDatabase, serviceImpl.editEwDatabase)
          .AddMethod(__Method_removeEwDatabase, serviceImpl.removeEwDatabase)
          .AddMethod(__Method_addVariationToSongDatabase, serviceImpl.addVariationToSongDatabase)
          .AddMethod(__Method_removeVariationFromSongDatabase, serviceImpl.removeVariationFromSongDatabase)
          .AddMethod(__Method_syncEwDatabase, serviceImpl.syncEwDatabase)
          .AddMethod(__Method_insertEwSongIds, serviceImpl.insertEwSongIds).Build();
    }

  }
}
#endregion
